# Generated by Django 4.1.4 on 2023-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charge',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
